### ISSUE TITLE
Sharing iP code quality check results [for @Shannonwje]

### ISSUE THREAD

**Issue by nus-pe-script** [Shannonwje/duke#1]
We did an automated analysis of your code to detect potential areas to improve the code quality. We are sharing the results below, to help you improve the code further.

IMPORTANT: Note that the script looked for **just a few easy-to-detect problems only**, and **at-most one example is given** i.e., there can be other areas/places to improve.

### Aspect: Tab Usage

No easy-to-detect issues :+1: 

### Aspect: Brace Style

No easy-to-detect issues :+1: 

### Aspect: Package Name Style

No easy-to-detect issues :+1: 

### Aspect: Class Name Style

No easy-to-detect issues :+1: 

### Aspect: Dead Code

Example from [`src/main/java/duke/Duke.java` line `47`](https://github.com/Shannonwje/duke/blob/c34b9d99bd68cd9a4911b2ef2d08010a11ac2f69/src/main/java/duke/Duke.java#L47):
```java
                //addInNewTask(inputLine);
``` 

**Suggestion:** Remove dead code from the codebase.

### Aspect: Method Length

No easy-to-detect issues :+1:

**Comment by Shannonwje** [comment]
Hi, I have removed dead code from code base, thank you :)
